### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by tasmia2016831022** [ShahriarDhruvo/ERP-for-SUST#9]
Please update your readme file, so that more audience can have a good idea about your project. Also, somehow the link isn't working. Check it out also. TA & Good Luck ;P

**Comment by ShahriarDhruvo** [comment]
Readme file has been updated & link is now working(maybe that issue was with free hosting!). Thanks for your concern :)

**Comment by tasmia2016831022** [comment]
@ShahriarDhruvo  that's great!! 
Your project idea sounds promising. There's a lot to do in frontend (mobile view) maybe. :P
Hope you'll continue to upgrade it. Keep it up and good luck ❤️❤️
